### ISSUE TITLE
脚本报了SQL错误

### ISSUE THREAD

**Issue by flyzy2005** [91yun/91yuntest#11]
`警告：SQL语句有误<br />错误代码：<font color='red'>1366</font>；<br /> 错误信息：<font color='red'>Incorrect string value: '旦°㬮.' for column 'c' at row 1</font>`
![image](https://user-images.githubusercontent.com/16304483/45928131-3f5bf180-bf71-11e8-9c7a-96e4bc7ae9a9.png)

**Comment by 91yun** [comment]
你在最开始的时候host尽量输入英文.中文的话有些ssh软件不支持.会导致问题.
