### ISSUE TITLE
全国ping没有结果

### ISSUE THREAD

**Issue by rilyuuj** [91yun/91yuntest#12]
脚本运行到开始进行群过ping测试，之后不显示结果。如下：

```
===开始进行全国PING测试===
线路            节点数目        最快节点                                延迟            最慢节点                                延迟                                    平均延迟
                                                                                                                                        
===进行全国PING测试结束===
测试已经结束，测试结果已经生成在同目录下的91yuntest.log,可以使用cat 91yuntest.log查看。

```
是不是多了一列，对比ipip站点最后列表，发觉并没有平均延长这一栏，请确实http://www.ipip.net/ping.php?a=send&host=$1&area%5B%5D=china 地址仍然有效，谢谢。

**Comment by 91yun** [comment]
我目前测了下似乎没问题https://www.91yuntest.com/6RGv44。 是不是你服务器访问不了ipip.net
。

**Comment by rilyuuj** [comment]
> 我目前测了下似乎没问题[https://www.91yuntest.com/6RGv44。](https://www.91yuntest.com/6RGv44%E3%80%82) 是不是你服务器访问不了ipip.net
> 。

可以访问的呀，用xshell打开浏览器都能正常访问，上面的连接我用自己的地址替换$1后也得不到结果呢，大佬
